# Example Astropix3 config
#
# The following yaml should comply to the structure below.
# It is important, that the order of configbits under the config section, corresponds to the actual order in the chip --> Genau das hat Nicolas mir auch gesagt
#
# astropix<version>:
#   geometry:
#       cols: <number of cols>
#       rows: <number of rows>
#   config:
#       <group-name>:
#           <configbit-name>: [<number of bits>, <value>]
#   ...
#
---
astropix_lf_test1:
    general:
        sampleclockperiod_ns: 10
    geometry:
        cols: 3
        rows: 1
    configcards:
        voltagecard:
            pos: 4
            dacs: [0, 0, 1.1, 1, 0, 0, 0.8, 1.2]
        injectioncard:
            pos: 3
    config:
        column_control:             # Test Chip with only 3 Pixels!
            EnInj0:         [1, 0b1]  # Enable Injection Test Signal input for Pixel 0
            RamWr0:         [5, 0b11111]
            Amp0:           [1, 0b0]  #Connect Pixel 0 with multiplexer to AO Chip Output
            Inj0:           [1, 0b1]
            RamIn0:         [1,0]
            EnB_HBRec0:     [1,1]
            EnInj1:         [1, 1]
            RamWr1:         [5, 0]
            Amp1:           [1, 1]
            Inj1:           [1, 1]
            RamIn1:         [1,1]
            EnB_HBRec1:     [1,0]
            EnInj2:         [1, 0]
            RamWr2:         [5, 0]
            Amp2:           [1, 0]
            Inj2:           [1, 0]
            RamIn2:         [1,0]
            EnB_HBRec2:     [1,1]

        bias_block:
            idac15:         [6,0]
            idac14:         [6,0]
            idac13:         [6,5] #pfoll
            idac12:         [6,10] #phb
            idac8:          [6,0] #pdac
            idac11:         [6,0] #nbias
            idac10:         [6,0]
            VNBiasComp:     [6,10]
            VN:             [6,15]
            idac6:          [6,1]                   # VNFB
            idac7:          [6,1]                   # BLRes
            VNSF:           [6,1] #sf
            idac3:          [6,10]                   # VPLOAD
            idac2:          [6,0]
            VNBiasRec2:     [6,0]
            VNBiasRec:      [6,0]

        vdac_block:
            BL:             [8,145]    # 142 = 1/1.8 *255 theoretisch! 145
            Vth:            [8,173]    # 156 = 1.1/1.8 *255 159
            Vcasc:          [8,150]    # 170 = 1.2/1.8 *255 173